language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - 1.8.7
  - ree
matrix:
  allow_failures:
    - rvm:
      - ruby-head
      - jruby-18mode
      - jruby-19mode
