language: ruby
rvm:
  - 2.1.2
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - rbx-2
  - jruby-19mode
  - jruby-18mode

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
