language: ruby
before_install: gem update --system && gem install bundler
rvm:
  - 2.3.3
  - 2.2.5
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree
  - jruby-19mode
  - jruby-18mode

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
